In [76]:
import sgp4

import importlib.metadata

version = importlib.metadata.version('sgp4')
print(version)
from sgp4.api import accelerated

2.27

In [77]:
import pandas as pd
import sys
import os
from pathlib import Path

from sgp4.api import accelerated

In [78]:
from sgp4.api import Satrec

s = '1 25544U 98067A   19343.69339541  .00001764  00000-0  38792-4 0  9991'
t = '2 25544  51.6439 211.2001 0007417  17.6667  85.6398 15.50103472202482'
satellite = Satrec.twoline2rv(s, t)

jd, fr = 2458826.5, 0.8625
e, r, v = satellite.sgp4(jd, fr)
e

print(r)  # True Equator Mean Equinox position (km)
print(v)  # True Equator Mean Equinox velocity (km/s)

(-6088.922358183078, -936.1367482888298, -2866.4408776941464)
(-1.5255342771668234, -5.5384966257541395, 5.068164791538606)

In [83]:
orbcomData=pd.read_csv('Orbcomm2026test.csv',skiprows=9)
orbcomData2hlater=pd.read_csv('Orbcomm2026later.csv',skiprows=9)
orbcomData

,\outl0\strokewidth0 \strokec2 OBJECT_NAME,OBJECT_ID,EPOCH,MEAN_MOTION,ECCENTRICITY,INCLINATION,RA_OF_ASC_NODE,ARG_OF_PERICENTER,MEAN_ANOMALY,EPHEMERIS_TYPE,CLASSIFICATION_TYPE,NORAD_CAT_ID,ELEMENT_SET_NO,REV_AT_EPOCH,BSTAR,MEAN_MOTION_DOT,MEAN_MOTION_DDOT\
0,ORBCOMM FM06,1997-084G,2026-10-05T21:28:37.955136,14.477825,0.000177,45.0133,239.6601,315.5269,72.5343,0.0,U,25118.0,999.0,51043.0,0.000244,0.000008,0\
1,ORBCOMM FM04,1998-007C,2026-10-06T04:05:19.148928,14.358918,0.003912,107.9618,37.8387,134.5775,225.8569,0.0,U,25159.0,999.0,49252.0,0.000232,0.000005,0\
2,ORBCOMM FM19,1998-046C,2026-10-06T04:58:21.273888,14.396645,0.000464,44.9934,75.7636,151.4158,18.3922,0.0,U,25415.0,999.0,47277.0,0.000230,0.000006,0\
3,ORBCOMM FM20,1998-046D,2026-10-06T03:51:05.876352,14.381932,0.000175,44.9932,85.1506,149.0725,211.0226,0.0,U,25416.0,999.0,47276.0,0.000183,0.000004,0\
4,ORBCOMM FM27,1998-053G,2026-10-06T01:00:49.684608,14.393057,0.000160,45.0043,168.7532,28.9157,331.1781,0.0,U,25481.0,999.0,46620.0,0.000208,0.000005,0\
5,ORBCOMM FM32,1999-065C,2026-10-05T16:13:42.568032,14.372626,0.000785,45.0168,10.1945,242.5089,117.4961,0.0,U,25982.0,999.0,40298.0,0.000195,0.000004,0\
6,ORBCOMM FM109,2014-040A,2026-10-06T01:04:16.425120,14.589339,0.000177,47.0029,287.3240,330.9287,29.1500,0.0,U,40086.0,999.0,65053.0,0.000083,0.000002,0\
7,ORBCOMM FM110,2015-081D,2026-10-06T02:44:48.988032,14.589843,0.000305,47.0013,196.8894,238.5128,121.5459,0.0,U,41182.0,999.0,57382.0,0.000104,0.000003,0\
8,ORBCOMM FM118,2015-081E,2026-10-05T19:23:56.030496,14.588319,0.000316,47.0036,198.7113,190.7645,169.3174,0.0,U,41183.0,999.0,57388.0,0.000105,0.000003,0\
9,ORBCOMM FM112,2015-081F,2026-10-05T22:44:39.598656,14.589762,0.000263,46.9975,106.4496,350.8895,9.1942,0.0,U,41184.0,999.0,57512.0,0.000079,0.000002,0\
10,ORBCOMM FM113,2015-081G,2026-10-06T03:11:41.751168,14.589468,0.000153,46.9994,106.0021,343.8237,16.2600,0.0,U,41185.0,999.0,57513.0,0.000071,0.000002,0\
11,ORBCOMM FM108,2015-081J,2026-10-05T13:04:46.767936,14.589950,0.000226,47.0062,20.3703,321.1748,38.8975,0.0,U,41187.0,999.0,57619.0,0.000091,0.000003,0\
12,ORBCOMM FM117,2015-081K,2026-10-05T13:55:18.893856,14.589778,0.000257,47.0028,18.8147,331.5463,28.5282,0.0,U,41188.0,999.0,57624.0,0.000096,0.000003,0\
13,ORBCOMM FM116,2015-081L,2026-10-05T23:18:46.680768,14.589785,0.000168,47.0007,106.7637,217.0655,143.0116,0.0,U,41189.0,999.0,57511.0,0.000081,0.000002,0\
14,},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
print(orbcomData.loc[1])

\outl0\strokewidth0 \strokec2 OBJECT_NAME                  ORBCOMM FM04
OBJECT_ID                                                     1998-007C
EPOCH                                        2026-10-06T04:05:19.148928
MEAN_MOTION                                                   14.358918
ECCENTRICITY                                                   0.003912
INCLINATION                                                    107.9618
RA_OF_ASC_NODE                                                  37.8387
ARG_OF_PERICENTER                                              134.5775
MEAN_ANOMALY                                                   225.8569
EPHEMERIS_TYPE                                                      0.0
CLASSIFICATION_TYPE                                                   U
NORAD_CAT_ID                                                    25159.0
ELEMENT_SET_NO                                                    999.0
REV_AT_EPOCH                                                    49252.0
BSTAR                                                          0.000232
MEAN_MOTION_DOT                                                0.000005
MEAN_MOTION_DDOT\                                                    0\
Name: 1, dtype: object

In [86]:
orbcomData.rename(columns={orbcomData.columns[-1]: 'MEAN_MOTION_DDOT'}, inplace=True)
orbcomData2hlater.rename(columns={orbcomData.columns[-1]: 'MEAN_MOTION_DDOT'}, inplace=True)

orbcomData.loc[0]

\outl0\strokewidth0 \strokec2 OBJECT_NAME                  ORBCOMM FM06
OBJECT_ID                                                     1997-084G
EPOCH                                        2026-10-05T21:28:37.955136
MEAN_MOTION                                                   14.477825
ECCENTRICITY                                                   0.000177
INCLINATION                                                     45.0133
RA_OF_ASC_NODE                                                 239.6601
ARG_OF_PERICENTER                                              315.5269
MEAN_ANOMALY                                                    72.5343
EPHEMERIS_TYPE                                                      0.0
CLASSIFICATION_TYPE                                                   U
NORAD_CAT_ID                                                    25118.0
ELEMENT_SET_NO                                                    999.0
REV_AT_EPOCH                                                    51043.0
BSTAR                                                          0.000244
MEAN_MOTION_DOT                                                0.000008
MEAN_MOTION_DDOT                                                     0\
Name: 0, dtype: object

In [80]:
import math
import datetime as dt
from sgp4.api import Satrec, WGS72, jday,SatrecArray

In [97]:

satArr =[]
rv_array_init=[]
rv_array_end=[]
for isat in range(len(orbcomData)-1):
    sat = Satrec()
    date_str_init = orbcomData.iloc[isat].EPOCH
    date_str_end = orbcomData2hlater.iloc[isat].EPOCH
    sat_init_time = dt.datetime.fromisoformat(date_str_init).replace(tzinfo=dt.timezone.utc)
    sat_end_time = dt.datetime.fromisoformat(date_str_end).replace(tzinfo=dt.timezone.utc)

    epoch = dt.datetime(1949, 12, 31, 0, 0, tzinfo=dt.timezone.utc)
    delta = sat_init_time - epoch
    days_since_1949 = delta.total_seconds() / 86400

    # 1. Parse mean motion derivatives correctly
    mm_dot = float(orbcomData.loc[isat].MEAN_MOTION_DOT)
    mm_ddot = float(orbcomData.loc[isat].MEAN_MOTION_DDOT[:-1])
    mm = float(orbcomData.loc[isat].MEAN_MOTION)

    # 2. Convert TLE/OMM units to SGP4 native units (Revolutions/Day -> Radians/Minute)
    # 2pi / 1440 min = 0.004363323129985824
    ndot = mm_dot * (2 * math.pi / (1440.0 ** 2))
    nddot = mm_ddot * (2 * math.pi / (1440.0 ** 3))
    no_kozai = mm * (2 * math.pi / 1440.0)

    sat.sgp4init(
        WGS72,
        'i',
        int(orbcomData.iloc[isat].NORAD_CAT_ID),
        days_since_1949,
        orbcomData.loc[isat].BSTAR,
        ndot,        # Corrected unit
        nddot,       # Corrected unit
        orbcomData.loc[isat].ECCENTRICITY,
        math.radians(orbcomData.loc[isat].ARG_OF_PERICENTER),
        math.radians(orbcomData.loc[isat].INCLINATION),
        math.radians(orbcomData.loc[isat].MEAN_ANOMALY),
        no_kozai,    # Corrected unit
        math.radians(orbcomData.loc[isat].RA_OF_ASC_NODE),
    )
    satArr.append(sat)

    # 3. Use 'sat' directly instead of 'Satrec(sat)'
    jd_init, fr_init = jday(sat_init_time.year, sat_init_time.month, sat_init_time.day, sat_init_time.hour, sat_init_time.minute, sat_init_time.second)
    jd_end, fr_end = jday(sat_end_time.year, sat_end_time.month, sat_end_time.day, sat_end_time.hour, sat_end_time.minute, sat_end_time.second)
    e,r_init, v_init = sat.sgp4(jd_init, fr_init)
    e,r_end, v_end = sat.sgp4(jd_end, fr_end)

    rv_array_init.append([r_init, v_init])
    rv_array_end.append([r_end, v_end])
sat_array = SatrecArray(satArr)

In [99]:
rv_array_end

[[(5641.910207764824, 3675.0617575165957, 2282.212018044805),
  (-1.705369540708608, 5.56090560710424, -4.720060651886306)],
 [(5482.189311823002, 4623.5575913334615, -4.4299644456269585),
  (1.4610096260059462, -1.7703885369269319, 7.08474006989057)],
 [(-4865.643719282954, 1338.4723268049065, 5036.168332328791),
  (-2.1534431675433785, -7.160992139377667, -0.1813132648656742)],
 [(608.5230953431103, 7117.720615437163, -4.636075956345512),
  (-5.263765693364974, 0.4472436121336839, 5.284897195568165)],
 [(-6957.866124042617, 1593.2104112120674, -0.12105247262156413),
  (-1.1736351262302356, -5.152625805207032, 5.288812741203783)],
 [(7140.163562982195, 325.129912525994, -1.9729028867033112),
  (-0.2386654506116525, 5.273430229795664, 5.285340500490954)],
 [(1951.8132132717406, -6799.266023793105, -1.5059643029693777),
  (4.920085648660378, 1.4165457937364878, 5.494649625259734)],
 [(-6920.688890647633, -1473.3443299969006, -1.4982921760141965),
  (1.0683584035841793, -5.005919909618337, 5.492957139452143)],
 [(-6917.197010085908, -1497.4982392568702, -2.2942190769109483),
  (1.086028947617258, -5.000846742938271, 5.49206745945643)],
 [(-1494.9540095680377, 6913.191221305136, -4.682155417535758),
  (-5.004935565229769, -1.0843361008952446, 5.494798445440568)],
 [(-1442.6350013495214, 6925.204888926208, -3.030592512938343),
  (-5.011998080510911, -1.047356741901816, 5.494316677230288)],
 [(6920.493304859368, 1462.768612300082, -1.6531542405254591),
  (-1.0623605452168745, 5.008466858104883, 5.495232786251178)],
 [(6942.902981846233, 1351.0143665659552, -3.670004331770302),
  (-0.980255872818028, 5.025730189967383, 5.49515765003907)],
 [(-1495.8876425683359, 6915.783990482412, -3.015392777680351),
  (-5.0025116933396525, -1.0847322845890213, 5.49296188842359)]]

In [92]:

satArr2hlater =[]
rv_array_init_2h_later=[]
#rv_array_2h_later_end=[]
for isat in range(len(orbcomData2hlater)-1):
    sat = Satrec()
    date_str_init = orbcomData2hlater.iloc[isat].EPOCH
    #date_str_end = orbcomData2hlater.iloc[isat].EPOCH
    sat_init_time = dt.datetime.fromisoformat(date_str_init).replace(tzinfo=dt.timezone.utc)
    #sat_end_time = dt.datetime.fromisoformat(date_str_end).replace(tzinfo=dt.timezone.utc)

    epoch = dt.datetime(1949, 12, 31, 0, 0, tzinfo=dt.timezone.utc)
    delta = sat_init_time - epoch
    days_since_1949 = delta.total_seconds() / 86400

    # 1. Parse mean motion derivatives correctly
    mm_dot = float(orbcomData.loc[isat].MEAN_MOTION_DOT)
    mm_ddot = float(orbcomData.loc[isat].MEAN_MOTION_DDOT[:-1])
    mm = float(orbcomData.loc[isat].MEAN_MOTION)

    # 2. Convert TLE/OMM units to SGP4 native units (Revolutions/Day -> Radians/Minute)
    # 2pi / 1440 min = 0.004363323129985824
    ndot = mm_dot * (2 * math.pi / (1440.0 ** 2))
    nddot = mm_ddot * (2 * math.pi / (1440.0 ** 3))
    no_kozai = mm * (2 * math.pi / 1440.0)

    sat.sgp4init(
        WGS72,
        'i',
        int(orbcomData2hlater.iloc[isat].NORAD_CAT_ID),
        days_since_1949,
        orbcomData2hlater.loc[isat].BSTAR,
        ndot,        # Corrected unit
        nddot,       # Corrected unit
        orbcomData2hlater.loc[isat].ECCENTRICITY,
        math.radians(orbcomData2hlater.loc[isat].ARG_OF_PERICENTER),
        math.radians(orbcomData2hlater.loc[isat].INCLINATION),
        math.radians(orbcomData2hlater.loc[isat].MEAN_ANOMALY),
        no_kozai,    # Corrected unit
        math.radians(orbcomData2hlater.loc[isat].RA_OF_ASC_NODE),
    )
    satArr.append(sat)

    # 3. Use 'sat' directly instead of 'Satrec(sat)'
    jd_init, fr_init = jday(sat_init_time.year, sat_init_time.month, sat_init_time.day, sat_init_time.hour, sat_init_time.minute, sat_init_time.second)
    #jd_end, fr_end = jday(sat_end_time.year, sat_end_time.month, sat_end_time.day, sat_end_time.hour, sat_end_time.minute, sat_end_time.second)
    e,r_init, v_init = sat.sgp4(jd_init, fr_init)
    #r_end, v_end = sat.sgp4(jd_end, fr_end)

    rv_array_init_2h_later.append([r_init, v_init])
    #rv_array_end.append([r_end, v_end])
sat_array = SatrecArray(satArr)

In [145]:
import numpy as np
arr_init = np.array(rv_array_init_2h_later)
arr_end = np.array(rv_array_end)

# 2. Vectorized subtraction: calculate all delta_r and delta_v at once
# arr_init[:, 0] gets all r vectors; arr_init[:, 1] gets all v vectors
delta_r = arr_init[:, 0, :] - arr_end[:, 0, :]
delta_v = arr_init[:, 1, :] - arr_end[:, 1, :]

#print(delta_r)
# 4. Construct the RSW / RTN Local Orbital Frame unit vectors from the reference state
# R-axis: Radial (outward from Earth center along position vector)
e_r = arr_init[:, 0, :]
e_r_norms = np.linalg.norm(e_r, axis=1, keepdims=True)
e_r = e_r/e_r_norms
#print(e_r_norms.shape)
# W-axis (or N): Cross-track (normal to the orbital plane, along angular momentum)
h = np.cross(arr_init[:, 0, :], arr_init[:, 1, :])
e_w = h / np.linalg.norm(h,axis=1, keepdims=True)

# S-axis: Along-track (perpendicular to R and W, aligned roughly with velocity)
e_s = np.cross(e_w, e_r)

# 5. Project the Cartesian error vector into the RSW frame
radial_error = np.sum(delta_r * e_r , axis=1,keepdims=True)      # R: Radial error
along_track_error = np.sum(delta_r*e_s,axis=1,keepdims=True)    # S: Along-track error
cross_track_error = np.sum(delta_r*e_w,axis=1,keepdims=True)    # W: Cross-track error

print(radial_error)
print(along_track_error)
print(cross_track_error)
# 3. Calculate norms along the last axis (axis=1) and scale by 1000
dr_array = np.linalg.norm(delta_r, axis=1) * 1000
dv_array = np.linalg.norm(delta_v, axis=1) * 1000

#print(dr_array)
#print(dv_array)

[[-0.0654362 ]
 [-0.0450278 ]
 [ 0.00863854]
 [ 0.00011226]
 [ 0.01696566]
 [ 0.09254084]
 [ 0.01430414]
 [ 0.04194734]
 [ 0.06181058]
 [ 0.03452038]
 [ 0.04268589]
 [ 0.06688566]
 [ 0.07118301]
 [ 0.07024522]]
[[-0.66925543]
 [-0.19845389]
 [-0.18075609]
 [ 0.01231872]
 [-0.05412959]
 [-0.24117982]
 [-0.05538284]
 [ 0.09320705]
 [ 0.00801921]
 [-0.45925489]
 [-0.03550423]
 [ 0.37113782]
 [ 0.26731666]
 [-0.38281704]]
[[ 2.02047898e-01]
 [-1.09654486e-01]
 [ 2.88853611e-02]
 [-7.97408991e-06]
 [-5.83335699e-02]
 [-2.31382257e-01]
 [-4.10995925e-02]
 [-1.83030538e-01]
 [-2.60764137e-01]
 [-1.37264311e-01]
 [-1.40501327e-01]
 [-3.35380321e-01]
 [-2.85646503e-01]
 [-1.59322341e-01]]

In [68]:
from sgp4.api import jday
import numpy as np

jd1, fr1 = jday(2026, 10, 7, 12, 0, 0)
jd2, fr2 = jday(2026, 10, 7, 12, 0, 1)
e, r, v = sat_array.sgp4(np.array([jd1,jd1]),np.array( [fr1,fr1]))
print(e)
print(r)
print(v)

[[6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]]
[[[ -752.99823596 -2408.85428651 -1265.98482953]
  [ -752.99823596 -2408.85428651 -1265.98482953]]

 [[  565.36916394  1016.38104402  2568.43502224]
  [  565.36916394  1016.38104402  2568.43502224]]

 [[ 1041.50930865  2244.2517914   1370.72666745]
  [ 1041.50930865  2244.2517914   1370.72666745]]

 [[-1045.26489682  2600.74916894  -430.47476557]
  [-1045.26489682  2600.74916894  -430.47476557]]

 [[-2535.79886435  1052.70222373   688.16444997]
  [-2535.79886435  1052.70222373   688.16444997]]

 [[ 2431.2305504  -1457.07597063    40.0108047 ]
  [ 2431.2305504  -1457.07597063    40.0108047 ]]

 [[ -181.25464222 -2532.93144023  1186.90989147]
  [ -181.25464222 -2532.93144023  1186.90989147]]

 [[-1742.78195768  1066.04240335  1913.34614754]
  [-1742.78195768  1066.04240335  1913.34614754]]

 [[  -54.94103869  1919.11871277  2035.87417518]
  [  -54.94103869  1919.11871277  2035.87417518]]

 [[ 1417.4146327  -2142.13009344  1125.52373826]
  [ 1417.4146327  -2142.13009344  1125.52373826]]

 [[ 1950.11792595   352.4637687   1976.3601907 ]
  [ 1950.11792595   352.4637687   1976.3601907 ]]

 [[ 1451.17985849  1296.36458083 -2026.12804045]
  [ 1451.17985849  1296.36458083 -2026.12804045]]

 [[ 2096.24989589   618.66652012 -1764.81670126]
  [ 2096.24989589   618.66652012 -1764.81670126]]

 [[-1970.50750673   402.16045707 -1962.32976087]
  [-1970.50750673   402.16045707 -1962.32976087]]]
[[[  9.94620371   0.3088875   -6.51003105]
  [  9.94620371   0.3088875   -6.51003105]]

 [[  4.29992679 -10.5960018    3.21784283]
  [  4.29992679 -10.5960018    3.21784283]]

 [[ -7.27826565   7.14800436  -6.10648434]
  [ -7.27826565   7.14800436  -6.10648434]]

 [[ -7.40824345  -4.32434995  -8.22382208]
  [ -7.40824345  -4.32434995  -8.22382208]]

 [[ -5.1791149   -7.22621459  -7.90821535]
  [ -5.1791149   -7.22621459  -7.90821535]]

 [[  4.4419826    7.11981917  -8.42690658]
  [  4.4419826    7.11981917  -8.42690658]]

 [[  8.72558676  -3.99941839  -7.11786379]
  [  8.72558676  -3.99941839  -7.11786379]]

 [[ -8.2961907   -8.02310926  -3.05245628]
  [ -8.2961907   -8.02310926  -3.05245628]]

 [[-11.90634544   0.42419109  -0.70979693]
  [-11.90634544   0.42419109  -0.70979693]]

 [[  5.62483772   7.60483145   7.29607526]
  [  5.62483772   7.60483145   7.29607526]]

 [[ -4.23291939  10.94070553   2.2025366 ]
  [ -4.23291939  10.94070553   2.2025366 ]]

 [[ -8.85898143   7.81436622  -1.34629744]
  [ -8.85898143   7.81436622  -1.34629744]]

 [[ -6.39705766   9.00107801  -4.44050523]
  [ -6.39705766   9.00107801  -4.44050523]]

 [[  0.15650102 -11.61626261  -2.5315123 ]
  [  0.15650102 -11.61626261  -2.5315123 ]]]

In [45]:
from sgp4.api import SGP4_ERRORS
SGP4_ERRORS

{1: 'mean eccentricity is outside the range 0.0 to 1.0',
 2: 'nm is less than zero',
 3: 'perturbed eccentricity is outside the range 0.0 to 1.0',
 4: 'semilatus rectum is less than zero',
 5: '(error 5 no longer in use; it meant the satellite was underground)',
 6: 'mrt is less than 1.0 which indicates the satellite has decayed'}

In [51]:
orbcomDataLater=pd.read_csv('Orbcomm2026later.csv',skiprows=9)
orbcomDataLater

,\outl0\strokewidth0 \strokec2 OBJECT_NAME,OBJECT_ID,EPOCH,MEAN_MOTION,ECCENTRICITY,INCLINATION,RA_OF_ASC_NODE,ARG_OF_PERICENTER,MEAN_ANOMALY,EPHEMERIS_TYPE,CLASSIFICATION_TYPE,NORAD_CAT_ID,ELEMENT_SET_NO,REV_AT_EPOCH,BSTAR,MEAN_MOTION_DOT,MEAN_MOTION_DDOT\
0,ORBCOMM FM06,1997-084G,2026-10-07T07:10:24.445920,14.477847,0.000168,45.0133,232.8987,321.4381,191.5105,0.0,U,25118.0,999.0,51063.0,0.000242,0.000008,0\
1,ORBCOMM FM04,1998-007C,2026-10-07T06:50:26.647296,14.358932,0.003906,107.9620,40.1330,132.5608,227.8840,0.0,U,25159.0,999.0,49268.0,0.000229,0.000005,0\
2,ORBCOMM FM19,1998-046C,2026-10-07T00:35:52.285344,14.396655,0.000471,44.9936,71.8755,156.0389,295.9643,0.0,U,25415.0,999.0,47289.0,0.000224,0.000006,0\
3,ORBCOMM FM20,1998-046D,2026-10-06T03:51:05.876352,14.381932,0.000175,44.9932,85.1506,149.0725,211.0227,0.0,U,25416.0,999.0,47276.0,0.000183,0.000004,0\
4,ORBCOMM FM27,1998-053G,2026-10-06T09:20:35.037888,14.393063,0.000159,45.0045,167.1044,31.2675,328.8268,0.0,U,25481.0,999.0,46625.0,0.000212,0.000005,0\
5,ORBCOMM FM32,1999-065C,2026-10-07T06:35:51.436032,14.372642,0.000795,45.0167,2.6256,249.8502,110.1491,0.0,U,25982.0,999.0,40321.0,0.000191,0.000004,0\
6,ORBCOMM FM109,2014-040A,2026-10-06T07:38:44.285568,14.589342,0.000175,47.0029,286.0286,332.0210,28.0581,0.0,U,40086.0,999.0,65057.0,0.000086,0.000002,0\
7,ORBCOMM FM110,2015-081D,2026-10-07T03:24:00.283680,14.589855,0.000307,47.0013,192.0316,242.2390,117.8185,0.0,U,41182.0,999.0,57397.0,0.000111,0.000004,0\
8,ORBCOMM FM118,2015-081E,2026-10-07T04:16:23.448288,14.588335,0.000323,47.0035,192.2356,196.4143,163.6638,0.0,U,41183.0,999.0,57408.0,0.000112,0.000004,0\
9,ORBCOMM FM112,2015-081F,2026-10-06T20:06:37.931328,14.589764,0.000258,46.9973,102.2390,354.7696,5.3163,0.0,U,41184.0,999.0,57525.0,0.000073,0.000002,0\
10,ORBCOMM FM113,2015-081G,2026-10-07T00:33:41.574240,14.589474,0.000147,46.9995,101.7918,347.4054,12.6795,0.0,U,41185.0,999.0,57526.0,0.000072,0.000002,0\
11,ORBCOMM FM108,2015-081J,2026-10-07T07:48:41.294016,14.589970,0.000219,47.0064,11.9510,327.9661,32.1092,0.0,U,41187.0,999.0,57645.0,0.000100,0.000003,0\
12,ORBCOMM FM117,2015-081K,2026-10-07T05:22:01.669152,14.589796,0.000249,47.0028,11.0424,337.9164,22.1615,0.0,U,41188.0,999.0,57648.0,0.000105,0.000003,0\
13,ORBCOMM FM116,2015-081L,2026-10-06T22:19:21.620640,14.589788,0.000174,47.0009,102.2296,219.2710,140.8050,0.0,U,41189.0,999.0,57525.0,0.000073,0.000002,0\
14,},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

10 7 7 10 24
10 7 6 50 26
10 7 0 35 52
10 6 3 51 5
10 6 9 20 35
10 7 6 35 51
10 6 7 38 44
10 7 3 24 0
10 7 4 16 23
10 6 20 6 37
10 7 0 33 41
10 7 7 48 41
10 7 5 22 1
10 6 22 19 21